spring.application.name=Movie_Recommendation_System
spring.datasource.url=jdbc:postgresql://localhost:5432/Rating
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.file.name=logs/app.log
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation=DEBUG
logging.level.org.springframework.beans.factory=TRACE

server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=prathamv888@gmail.com
spring.mail.password=mwgidzkmratjtclc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
